### ISSUE TITLE
start page on small screens 

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/fundament#16]
On my iphone (current os) this page:
https://arthur-schnitzler.github.io/schnitzler-briefe-static/
looks like this:
![Hermann Bahr – Arthur Schnitzler](https://user-images.githubusercontent.com/11441262/200531848-54d5396e-2282-47ab-9a5c-a5ac9ab1e697.png)

as can be seen the title of the website on top of the image is not shown. the image has a gray bar underneath. 

the code can be found here:
https://github.com/arthur-schnitzler/schnitzler-briefe-static

and was built with 
https://github.com/acdh-oeaw/dse-static-cookiecutter

@ctot-nondef @csae8092

**Comment by ctot-nondef** [comment]
the "error" is actually expected behaviour - the image is being displayed in a bootstrap carousel component (wich is usually used to display miultiple images in a spinner - see https://getbootstrap.com/docs/4.0/components/carousel/) wich by default hides it's caption for all screen widths smaller than 768px

possible solutions:

exchange it for a jumbotron see https://github.com/arthur-schnitzler/schnitzler-briefe-static/pull/3

**Comment by ctot-nondef** [comment]
caveat of this might be that only one image can be displayed...

**Comment by ctot-nondef** [comment]
closing this issue as it is not a fundament problem but an issue specific to https://github.com/arthur-schnitzler/schnitzler-briefe-static
